### ISSUE TITLE
本レポジトリ（とりわけQuestions.yaml）のライセンスは具体的に何でしょうか？

### ISSUE THREAD

**Issue by CLRafaelR** [SingularitySociety/WorldModels#10]
@snakajima さま， @isamu さま， @sshiraki さま

下記リンク先の記事より，このレポジトリに掲載されている「『世界モデルを持たないLLM』にとって難しい質問のリストをオープンソース化」した旨拝見いたしました。

「世界モデルを持たないLLM」にとって難しい質問のリスト | Singularity Society
https://singularitysociety.org/articles/blog/2024-09-09/

ですが，こちらのレポジトリにはライセンスが何か明記されておりませんでしたので，差し支えなければ本レポジトリのライセンスをご教示いただきたくお願い申し上げます。例えば，MITなのか，Apache License 2.0なのか，CC-BY-*なのか，という点をご教示いただけましたら幸甚に存じます。

------

【質問背景】
本レポジトリのQuestions.yamlの内容を学習データとして商用利用可能なLLMを構築したり，Questions.yamlの各質問を参考に人手ないしLLMにより「『世界モデルを持たないLLM』にとって難しい質問から構成されるLLM訓練用データ」を作成したりしたいと考えております。そのため，このような用途でこちらのレポジトリのQuestions.yamlを利用してよいかお尋ねしたく存じます。

突然のご連絡にて不躾なお願いをし大変恐縮ではございますが，何卒ご検討いただきたくよろしくお願い申し上げます。

**Comment by isamu** [comment]
ご質問ありがとうございます！

package.jsonに記載していますが、このレポジトリはMITライセンスです。

https://github.com/SingularitySociety/WorldModels/blob/main/package.json#L6

**Comment by CLRafaelR** [comment]
@isamu さま

ご返信ありがとうございます！MITライセンスとのこと，承知いたしました。ご教示くださり御礼申し上げます。

package.jsonの確認，失念しておりました…（GitHubのAbout欄に記載がないな，LICENSEファイルもなさそうだな，と思ってそこで止まっておりました）

![image](https://github.com/user-attachments/assets/cdefbf38-a2eb-4ecb-a905-8e7e9592f2e3)

**Comment by CLRafaelR** [comment]
こちら解決いたしましたので，Closeいたします

**Comment by isamu** [comment]
ありがとうございます！！
ライセンスファイルも追加しました。
